### ISSUE TITLE
I2S: register I2S object to platform failed

### ISSUE THREAD

**Issue by faduchesne** [toverainc/willow#125]
hi ! I flashed with the updated firmware. flash success ! in the lot , I've lot this error : 

`I2S: register I2S object to platform failed`

**Comment by kristiankielhofner** [comment]
That error is expected - everything should be working just fine.

Can you confirm?

**Comment by faduchesne** [comment]
Yes ! I do . thx

**Comment by stintel** [comment]
Some details: this is because we call i2s_stream_init() twice - once for audio capture, another time for audio playback. This calls i2s_driver_install(), which throws the error because we already installed the driver. In ESP-IDF 5.0, the I2S driver has been redesigned, but we'd have to wait until ESP-ADF components have been adapted to this new driver.
