### ISSUE TITLE
Willow docker port conflicts with WIS docker ports used for WebRTC

### ISSUE THREAD

**Issue by nikito** [toverainc/willow#196]
I run both the WIS instance and the Willow docker on the same docker server. What I have noticed is that when the Willow docker tries to start, it wants to expose port 10000 in the container. However, WIS uses port 10000 so I get a conflict. To work around this I had to modify the Utils.sh to change the port to 20000 to avoid the issue. Thinking it may be a good idea to do this in the actual release code to avoid the problem for other users who may run the containers on the same server? (I know once 1.0 is released this will probably be less of, or not at all, an issue, but figure this may help out for developers). 😃

**Comment by kristiankielhofner** [comment]
Good catch!

As 1.0 overall comes together we need to take a good hard look at port assignments generally and establish some defaults that make sense.

For the Willow container, exposing port 10000 is kind of a goofy hack to give Windows users a chance to flash. I don't see a reason why not to remove it in 1.0 because with the web flasher (in development) and WAS OTA there really isn't a good reason to leave it.

**Comment by nikito** [comment]
Makes sense and figured that was the path this would move toward. 😃
