### ISSUE TITLE
Respeaker support?

### ISSUE THREAD

**Issue by jerome83136** [toverainc/willow#317]
Hello,
Great project! Really promising! I will definitely play with this nice toy you made for all of us 😁

I'm already using other software and hardware for voice application and I wonder if there is a chance other hardware will be supported in the future?

So concretely; is there a chance respeaker hardware will be supported ? https://wiki.seeedstudio.com/ReSpeaker/

This hardware is meant for voice applications with embedded voice treatment hardware. Of course this is not esp32 based; so it would require you to release and maintain an arm version of your software.

But there is a big community of arm users in the voice application and home automation world. So, supporting this kind of hardware would allow you making your public even larger 😉

Thank you for your feedback and if you cannot fulfill my request, please guys fulfill at least this one: never get yourself buyed or killed by GAFAMs 🙏😊

Best regards

**Comment by kristiankielhofner** [comment]
Thanks!

We have a generic Willow Linux client that hasn't been released. This will be long but I expect this will be a recurring topic so I want to put the time in to explain our position. My response here will serve as a draft for what we will likely provide on heywillow.io and elsewhere.

Plugging a microphone into a device and making it a voice interface seems obvious and practical in concept/theory. Unfortunately, what I've experienced over the past several years in trying to implement this via miscellaneous hardware, Linux, and software demonstrates it isn't practical in the real-world:

- Linux with all of the realtime configurations and patches available still isn't a realtime operating system like what we use on the ESP-BOX (FreeRTOS). Without the timing guarantees of a realtime operating system you have relatively wide variability just in terms of audio capture and execution with Linux fundamentally, which only gets worse and worse depending on what else the host system is doing. If you look at various projects attempting realtime audio on Linux you will start to understand how difficult and complex this issue is. Sometimes it can be made "good enough" but it often isn't.

- Audio on Linux is really messy in general. ALSA, Pulseaudio, Pipewire... There is no standard configuration across the Linux audio ecosystem and even when you "standardize" on Pulseaudio for compatibility with native Pulseaudio implementations and Pulseaudio via Pipewire there are still issues all over the place: varying buffers throughout the stack, hardware configurations, quirks in underlying drivers, etc. Plain ALSA is tough for other reasons. Then there's JACK which is a completely different animal.

- Varying microphones. Even just the Respeaker series comes in multiple different hardware configurations - i2s, USB, etc that each also have their own quirks due to variations in hardware design and drivers. The Respeaker series has also been more-or-less abandoned in terms of software support and just getting the i2s drivers to compile with your host OS and kernel can be a challenge (I last did this successfully a couple of months ago via some random fork I found on Github).

- Lack of coherent and consistent audio capture. The USB Respeaker alone comes with multiple firmware versions that change the number of output channels. There are also vast underlying differences with varying degrees of configurability in the chipsets some of these devices use (typically provided by XMOS or similar) that introduce even more quirks and variability from the frontend audio processing to the audio levels and format returned by the hardware. There are also varying sample rates supported by the underlying hardware which introduces another rub - audio captured by this hardware often needs to be resampled somewhere and this alone can have the tendency to introduce clicks, pops, varying CPU load, etc. I myself fairly regularly see wake/capture failures because of this with our limited scope and highly optimized software client.

- Doing everything in software. These approaches often don't even support the advanced frontend audio processing Willow does on ESP-BOX (AEC, BSS, VAD, etc) and attempting to do even a subset of this by chaining together software in the audio path introduces even more challenges in quality, variability, latency, and performance. We measure and benchmark performance down to at least the 10s of milliseconds range, which is a tall and nearly impossible order for this approach. The buffering alone is a disaster and I have yet to get our software client to provide the consistent timing we have with the ESP-BOX: variations in timing between wake word, speech command, and any follow-up consistently trips-up this approach. With Willow and an ESP-BOX you can throw wake word and speech/commands at it with nearly any variability in timing and it will do what you expect - even in "rapid fire" scenarios.

- Physical design and packaging. Audio hardware acoustics are a very real thing and without any consistency in terms of enclosures, physical layout, etc between devices there is even more fundamental variance in the audio returned from them.

- Stability and reliability. We routinely do real-world full-stack testing of performance, accuracy, and reliability. Our standard testbench for any change is 1000 loops from wake to TTS feedback on playback from an external audio source. Our maximum acceptable failure rate is 1% and more often than not it's actually 0. We also do fairly regularly do tests simulating a year's worth of voice sessions (10,000 - which is ~27/day across 365 days) while maintaining < 1% failure rates. I have zero confidence a Linux software implementation running on a Raspberry Pi or similar (especially with SD card) can possibly approach this. Without a lot of changes to the operating system to run completely read-only something as simple and routine as a power failure can take out a Linux-based device and even USB audio devices themselves flake out occasionally (because USB). An ESP-BOX is essentially impossible to break (we've never seen or heard of it) and there are other ESP-based devices that have been silently doing their job in challenging conditions for many, many years. This is what we and our users expect with Willow.

- Manageability. Many Willow users have five or more devices (I have at least 10, of course). With the Willow Application Server all configuration, updates, etc are managed centrally. Applying a configuration change is clicking a button and waiting ~10 seconds for all devices to reboot. We even randomize the reboot delay per device to not swarm your network/access points. This isn't possible with a Linux based approach without some extensive framework/tooling to manage these voice satellites. I've been using Linux for nearly 30 years and not even I want another half-dozen Linux systems to deal with - or even one. I test with Alexa/Echo devices that have been bulletproof for nearly a decade, this is what we are targeting with Willow.

- Performance. We recommend hardware configurations that can consistently execute voice commands in under 500ms (depending on hardware). For many users it's closer to half of that. Even with extensive tuning for specific configurations our Linux Willow client often has variability in the hundreds of milliseconds range (and this isn't specific to us) with best case performance still being worse than the ESP-BOX. The ESP-BOX beats my $500 Nvidia Jetson Orin Nano, which is pretty incredible.

- Connectivity. Wifi on Linux is yet-another can of worms in terms of supported hardware with wide ranges in feature support for things like frame aggregation, etc that only leads to even more variability - which Wifi already has enough of due to the fundamentals of RF, access points, spectrum utilization, etc. With the ESP-BOX we can control, configure, and optimize Wifi for this somewhat special use-case down to the chip, which also significantly contributes to the consistency of this approach.

- User experience. Willow ESP-BOX devices have 100% consistency in user experience - from flash/onboarding, to configuration, to visual and audible feedback. Our software client supports status via the LED ring on the USB Respeaker but even this has wide variability across Respeaker devices, and many external devices have no capability for feedback or it's baked in to the firmware on the device. Supporting external LCD displays across generic hardware is yet another wild challenge in terms of everything from SPI to i2c, resolution, drivers, software support, etc.

- Software packaging and distribution. There is endless variety with Linux systems - different architectures, Python/library versions, kernels, distros, drivers, etc. Our client can use docker with a host Pulseaudio implementation (via UNIX socket) to improve this but even it gets brittle pretty quickly when you need to deal with audio and hardware access from a docker container, differences in host audio support, etc. Then there are the people using podman, various container runtimes, etc that we've already experienced with Willow dev environments, WAS, and WIS. ALSA/Pulseaudio/Pipewire themselves have at least dozens of possible configuration options that introduce further variability.

- Advanced Willow functionality. Consider what Willow is already capable of as of our [latest release](https://youtu.be/qlhSEeWJ4gs). We're only just getting started but even things like Willow One Wake are next to impossible with the wide variability in hardware, timing, audio levels, etc with this approach. Our goal is to be the best voice interface in the world - even better than commercial devices. This goal will never be realized with a generic Linux/hardware approach.

- Economics. I understand why people are interested in this approach but the economics make no sense to me. The far-field-ish microphone devices of interest from the Home Assistant community range from $60 - $80 (or more), which makes the microphone itself more expensive than an entire ESP-BOX. By the time you add a Raspberry Pi or other host system you end up somewhere around 2-3x the cost for what is guaranteed to be a significantly worse experience. When you factor in the voice satellite pricing differences of Raspberry Pi + microphone based approaches you can buy an entire new homelab server with GPU to run HA and tons of other stuff and still come out ahead (my server configuration was $300 with Nvidia GPU).

- Supportability. We only release software we intend to support well and in the long-term. We're a very small team (three people, part time) and I'm not terribly keen on getting bogged down by the never-ending issues I've highlighted, especially when the end result will never be comparable to what we have today with the ESP-BOX series. This will only be frustrating to us and our users and time spent attempting to address these issues in vain only takes away from our overall goals. In short, attempting to support this approach is an impossible nightmare for all involved.

- Sourcing of hardware and assembly. You can buy 10 ESP-BOXes in a single order, get them shipped, open the package, and have them all up and running around your house in less time than it takes to flash an SD card and cobble together one Raspberry Pi-based device - at a fraction of the effort. There are supply challenges throughout the industry but Espressif has told us the ESP-BOX-3 will be manufactured in mass and ample quantity when it is available in the next month or so. I understand the journey and tinkering in a DIY approach is part of the fun but when you consider these issues it moves from fun to frustrating very quickly.

- Power usage. Raspberry Pi devices (and similar) are relatively low power but they don't come remotely close to an ESP-BOX where power consumption is measured in milliamps. By the time you add up the difference in power usage across a handful of devices you can have a more powerful "server" with GPU locally delivering blistering fast and highly accurate speech recognition and TTS while breaking even in power usage or even coming out ahead depending on the number of satellite devices.

- Expectations. Personally, I don't like the idea of people going out and spending money on hardware that's essentially guaranteed to not work at the minimum level we consider acceptable while causing a tremendous amount of frustration. I would go so far as to say it's unethical to recommend these configurations to users who are unaware of these fundamental issues and challenges without a ton of noted caveats - "YMMV". Users who will be expecting their implementation to be as usable as something they saw someone pull off in a demo video somewhere, and wondering why it isn't because this stuff is hard and complicated.

Due to all of these issues and more trying to provide the consistency, performance, accuracy, reliability, etc we currently have with the ESP-BOX series of hardware with a software client ranges from very difficult to fundamentally impossible. I'm reluctant to release our software client because it will always be incapable of meeting the goals and experience the entire project targets. I suspect in the end many users will abandon this approach (as I have many times), throw this hardware on a shelf, and go out and buy ESP-BOXes - wasting only more time and money in the process.

The only way commercial devices are able to work as well as they do with a Linux-based approach is to completely control the entire device from enclosure, to audio hardware, to Linux kernel/"distro", to actual software implementation, and more. Anyone who tries to replicate this with a random hodgepodge of thrown together hardware and software will only end up disappointed when comparing it to Willow or commercial devices.

Home Assistant is attempting this approach and while it's extremely early (10 days since release or so) the HA Community Forums, Github Issues, etc are already filled with users experiencing issues rooted in everything I've highlighted. I should also point out a lot of their implementation is based on the (excellent) Rhasspy project which is four years old, yet these issues persist and always will because of the fundamental issues noted above. Willow is eight months old and we're able to provide the high quality experience we do because of consistency throughout the entire stack - just like commercial devices.

All of that said, we're thrilled to see the progress Home Assistant has made in supporting voice. Home Assistant does very well in supporting and enabling choice by its users but we emphasize real-world usability and user experience even when it means we have to limit choice. While many of these Home Assistant-based implementations can potentially provide something reasonably usable in the real-world our emphasis is on providing something that always works very well (for as many people as possible) in the real-world. Unfortunately, this can only come by limiting choice and enforcing consistency. In the end users need to use what works "best" for them and we're happy to suggest that users interested in this approach attempt it solely via the Home Assistant ecosystem. In the end we all have the same goal - getting creepy and limited big tech out; emphasizing private and completely local approaches. I support any path a user takes to achieve that.

On the GAFAM/MAGMA/FAANG point, the use-case and monetization strategy for Willow has always been commercial/enterprise applications where Amazon/Google/etc have no business. Applications like healthcare where the hardware, form factor, management, security, integrations, regulatory environment, economics, etc make the overall approach by these players a fundamental non-starter.

**Comment by jerome83136** [comment]
Hello @kristiankielhofner,
Thank you for the very detailed and clear answer.
I clearly understand your point and I think you are 100% right in focusing on your target.

So let's not disturb you anymore with other clients like Raspberry, Respeaker, etc... which are kind of "out of scope" :-)

I just hope Willow will also let some open door for users (like me) who will want to achieve more complex integrations (APIs, MQTT, etc...)

Thank you again for creating this really cool project; I'm impatient of testing it with my (being delivered) ESP BOX ;-)

Best regards

**Comment by kristiankielhofner** [comment]
I'm glad my rant didn't scare you off!

Now that we have solid fundamentals - Willow itself, Willow Application Server, Willow Inference Server, new web ui, etc integrations and applications are our next focus! The Willow Application Server is called that for a reason :).

As one example, we have already [started working on MQTT support](https://github.com/toverainc/willow/issues/314) via WAS. Our goal is for WAS to supplement/augment Home Assistant and other supported platforms with voice interface/assistant functionality in WAS via integrations, modules, and applications - including custom user ones. Willow on the ESP-BOX is actually fairly dumb beyond the interface and advanced audio processing. It will end up essentially being a voice terminal interface to WAS which will take on more and more of the heavy lifting for this kind of functionality. Not only does it not make sense to burden a device that should dedicate every available cycle to high quality audio, Python and WAS is much easier and faster to develop for when compared to C on a microcontroller. It's also much easier to work with in terms of upgrades - new functionality can be implemented via WAS without requiring many/any changes to Willow itself (OTA updates for each device, etc). Pull new WAS docker container, done.

We have a general sense from users and our own frustrations regarding the Home Assistant mix of Python code, increasingly complex YAML, etc which we feel is really starting to show some limitations when extended to voice interfaces, assistants, etc. Our intention is to make programming interfaces for this functionality solely available via Python which we feel should be a good mix of approachability, flexibility, and power. We already have some extremely simple and light examples for ChatGPT/self-host LLMs, Google Calendar, e-mail, etc in the works.

We likely won't ever have the approachability and ease of Home Assistant native voice interfaces but our focus is and will continue to be a platform agnostic voice platform for "power users" who are looking for higher performance, higher quality, and more flexibility with emphasis on a completely private and locally hosted approach.

Let us know when you get your ESP-BOX! The good news is the supply shortages should be remedied soon as Espressif has ramped up manufacturing with the ESP-BOX-3 which should be widely available within the next month or so. Going back to the discussion above - the points I made regarding the ESP-BOX are moot if you can't get them :).

**Comment by X-Ryl669** [comment]
There are other point to consider. In Rhasspy, the ASR result is run into an (internal) intent matcher, so even with a very bad speech recognition, most of the time, the final intent is recognized well. However, it doesn't integrate well with Home Assistant (it's redundant with HA's own ASR and intent recognition) and doesn't really fit well with continuous audio streaming on the network for the satellite.

Also, on Rhasspy, you can customize the wake word with OWW. This can't be done on the ESP BOX (or not cheap, IIUC).

For example, in HA, fasterwhisper doesn't work at all with french, so we have to rely on DeepSpeech for a working system and only Rhasspy performs well for this.

**Comment by kristiankielhofner** [comment]
We have plans leveraging the Willow Application Server (WAS) and the Willow Inference Server (WIS) to apply state of the art matching of commands. With the GPU-focus of WIS we have plenty of options in terms of how to implement this while maintaining the speed and accuracy Willow provides today.

I responded to your other issue regarding custom wake words. If you follow the OWW/HA Github Issues, Discord, Community Forums, etc you will start to see the OWW custom training process doesn't currently work very well in practice, with many users complaining they have to repeat the wake word several times, speak loudly and clearly, etc. There are also many reports of these issues with the wake words provided "out of box". This is is a very hard and fundamental problem to address that applies to all voice interfaces, including commercial solutions and Willow itself. In our view if you have to repeat yourself multiple times, use specific cadence, etc your voice assistant is broken and nearly useless. We've done significant testing with the HA implementation and have experienced this ourselves.

Faster-whisper with the typical models used by HA doesn't work well with French because it doesn't work very well in any language - it's just even worse in French. Running on CPU with tiny is already very slow and it's a very poor quality model. Base is significantly slower and still not very good. With Willow and substantial user feedback over the past six months we have learned that small with beam size 2 should be considered the bare minimum in terms of speech recognition models, even with the drastically superior audio quality provided by Willow and the ESP-BOX.

This is a fundamental problem and you can see from our [benchmarks](https://heywillow.io/components/willow-inference-server/#benchmarks) that even the fastest, most power hungry, and expensive CPUs take 641ms to transcribe 3.8 seconds of speech on a > $1000 CPU (AMD ThreadRipper). We have many users that go "all out" and use Whisper large-v2 with beam size 5, which provides incredible accuracy across a wide variety of languages (including French) for even very complex grammar. Looking at the comparison benchmarks you can see this is still so fast on even the cheapest GPUs like the GTX 1070 in the end it barely matters.

I should note that both faster-whisper and WIS use the same underlying engine and models. The WIS comparison benchmarks on CPU more-or-less match what you get with faster-whisper (WIS is actually slightly faster). The Raspberry PI comparison benchmarks were done with faster-whisper using the exact same parameters HA uses.

The word error rates (WER) provided by [OpenAI tell this story](https://github.com/openai/whisper#available-models-and-languages). Note this chart is for the large-v2 model, with smaller models getting significantly worse as you move down.

Between poor wake word accuracy, transcription, and speed it's faster, easier, and far less frustrating to take your phone out of your pocket and do whatever you need to do there.

Note that while this may seem very critical HA/Esphome and Willow are different projects with different goals and wildly different architectures as a result to meet those goals. There are pros and cons to both projects and we're happy for users to use what works best for them.
